// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {scheduler} from '../models';
import {schedule} from '../models';
import {attendance} from '../models';

export function CheckIn():Promise<main.CheckResult>;

export function CheckOut():Promise<main.CheckResult>;

export function GetAutostartEnabled():Promise<boolean>;

export function GetNextReminder():Promise<scheduler.NextReminder>;

export function GetSchedule():Promise<schedule.Schedule>;

export function GetSettings():Promise<schedule.Settings>;

export function GetTodayStatus():Promise<attendance.DailyStatus>;

export function GetURLs():Promise<schedule.URLs>;

export function SaveSchedule(arg1:schedule.Schedule):Promise<void>;

export function SaveSettings(arg1:schedule.Settings):Promise<void>;

export function SaveURLs(arg1:schedule.URLs):Promise<void>;

export function ShutdownCheckOut():Promise<main.CheckResult>;

export function ShutdownSkip():Promise<void>;
