// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIn() {
  return window['go']['main']['App']['CheckIn']();
}

export function CheckOut() {
  return window['go']['main']['App']['CheckOut']();
}

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetNextReminder() {
  return window['go']['main']['App']['GetNextReminder']();
}

export function GetSchedule() {
  return window['go']['main']['App']['GetSchedule']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTodayStatus() {
  return window['go']['main']['App']['GetTodayStatus']();
}

export function GetURLs() {
  return window['go']['main']['App']['GetURLs']();
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveURLs(arg1) {
  return window['go']['main']['App']['SaveURLs'](arg1);
}

export function ShutdownCheckOut() {
  return window['go']['main']['App']['ShutdownCheckOut']();
}

export function ShutdownSkip() {
  return window['go']['main']['App']['ShutdownSkip']();
}
